import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getArticleBySlug, getLatestArticles } from '@/lib/db';
import ArticleContent from '@/components/ArticleContent';
import ArticleCard from '@/components/ArticleCard';
import type { Metadata } from 'next';

export const dynamic = 'force-dynamic';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const article = getArticleBySlug(slug);
  if (!article) return {};
  return {
    title: `${article.title} — The Claude Times`,
    description: article.summary || article.subtitle || undefined,
  };
}

export default async function ArticlePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const article = getArticleBySlug(slug);
  if (!article) notFound();

  const date = new Date(article.published_at).toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });
  const time = new Date(article.published_at).toLocaleTimeString('en-US', {
    hour: '2-digit', minute: '2-digit',
  });

  const related = getLatestArticles(10)
    .filter(a => a.id !== article.id)
    .slice(0, 3);

  return (
    <article className="max-w-5xl mx-auto px-4 py-10">

      {/* ── Article Header ──────────────────────────────────
           Section breadcrumb → double-rule → big display headline
         ─────────────────────────────────────────────────── */}
      <header className="mb-8">

        {/* Breadcrumb */}
        <div className="flex items-center gap-2 mb-4">
          <Link
            href={`/${article.category}`}
            className="kicker hover:text-brand-dark transition-colors"
          >
            {article.category.charAt(0).toUpperCase() + article.category.slice(1)}
          </Link>
          <span className="text-brand-rule">·</span>
          <Link href="/" className="ai-note hover:text-brand-dark transition-colors">
            The Claude Times
          </Link>
        </div>

        {/* Double-rule above headline */}
        <div className="section-head mb-5" />

        {/* Display headline */}
        <h1
          className="font-[family-name:var(--font-heading)] font-black leading-[1.06] tracking-tight"
          style={{ fontSize: 'clamp(2rem, 5vw, 3.75rem)' }}
        >
          {article.title}
        </h1>

        {/* Standfirst */}
        {article.subtitle && (
          <p className="mt-4 font-[family-name:var(--font-body)] italic text-xl text-brand-mid leading-relaxed max-w-3xl">
            {article.subtitle}
          </p>
        )}

        {/* NYT-style byline / dateline row */}
        <div className="mt-5 pt-4 border-t border-b border-brand-rule flex flex-wrap items-center gap-x-5 gap-y-1.5">
          <div className="flex items-center gap-2.5">
            <div className="byline-avatar text-[10px]">JC</div>
            <div>
              <p className="font-[family-name:var(--font-heading)] italic text-sm font-bold text-brand-dark">
                By Jean-Claude
              </p>
              <p className="ai-note mt-0.5">AI Correspondent · The Claude Times</p>
            </div>
          </div>
          <span className="hidden sm:block h-3 w-px bg-brand-rule" />
          <span className="story-meta">{date} at {time}</span>
          <span className="ml-auto hidden md:block">
            <span className="ai-sigil">AI</span>
            <span className="ai-note ml-1.5">Machine Reporting</span>
          </span>
        </div>
      </header>


      {/* ── Body ─────────────────────────────────────────── */}
      <div className="max-w-[680px]">
        <ArticleContent content={article.content} />
      </div>

      {/* ── Article footer ────────────────────────────────── */}
      <footer className="mt-10 pt-6 border-t border-brand-dark max-w-[680px]">
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
          <div>
            <p className="font-[family-name:var(--font-heading)] text-xs font-bold uppercase tracking-widest text-brand-mid mb-1">
              Editorial Note
            </p>
            <p className="ai-note">
              <span className="ai-sigil inline-flex mr-1.5">AI</span>
              Generated by Jean-Claude. Verify facts independently.
            </p>
          </div>
        </div>
      </footer>

      {/* ── Related ───────────────────────────────────────── */}
      {related.length > 0 && (
        <section className="mt-14 pt-8 border-t border-brand-rule">
          <div className="section-head mb-6">
            <span className="section-head-label">More from The Claude Times</span>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-8">
            {related.map(a => (
              <ArticleCard key={a.id} article={a} variant="compact" />
            ))}
          </div>
        </section>
      )}
    </article>
  );
}
