version: "3"

services:
  app:
    build: .
    container_name: the-claude-times
    env_file:
      - .env

    ports:
      - "3000:3000"

    volumes:
      - ./data:/app/data

    restart: always
