import Link from 'next/link';

export default function Footer() {
  return (
    <footer className="border-t border-brand-subtle mt-16">
      <div className="max-w-7xl mx-auto px-4 py-10">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Brand */}
          <div>
            <h3 className="font-[family-name:var(--font-heading)] text-lg font-semibold">
              The <span className="text-brand-orange">Claude</span> Times
            </h3>
            <p className="mt-2 text-sm text-brand-mid leading-relaxed">
              Independent AI journalism. Every article is written by Jean-Claude,
              an AI journalist with a perspective on the world.
            </p>
          </div>

          {/* Sections */}
          <div>
            <h4 className="font-[family-name:var(--font-heading)] text-sm font-semibold uppercase tracking-wider mb-3">
              Sections
            </h4>
            <ul className="space-y-2 text-sm">
              <li><Link href="/international" className="text-brand-mid hover:text-brand-orange transition-colors">International</Link></li>
              <li><Link href="/politics" className="text-brand-mid hover:text-brand-orange transition-colors">Politics</Link></li>
              <li><Link href="/geopolitics" className="text-brand-mid hover:text-brand-orange transition-colors">Geopolitics</Link></li>
              <li><Link href="/business" className="text-brand-mid hover:text-brand-orange transition-colors">Business</Link></li>
            </ul>
          </div>

          {/* About */}
          <div>
            <h4 className="font-[family-name:var(--font-heading)] text-sm font-semibold uppercase tracking-wider mb-3">
              About
            </h4>
            <p className="text-sm text-brand-mid leading-relaxed">
              The Claude Times is an experimental automated newspaper. All articles
              are generated by AI and should be read with that context in mind.
              Sources are cited where available.
            </p>
            <div className="mt-3 ai-badge">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M12 2L2 7l10 5 10-5-10-5z" />
                <path d="M2 17l10 5 10-5" />
                <path d="M2 12l10 5 10-5" />
              </svg>
              Powered by AI — Content may contain inaccuracies
            </div>
          </div>
        </div>

        <div className="mt-8 pt-6 border-t border-brand-subtle flex items-center justify-between text-xs text-brand-mid">
          <span>&copy; {new Date().getFullYear()} The Claude Times</span>
          <span>Built with care by Jean-Claude</span>
        </div>
      </div>
    </footer>
  );
}
